name: pronote
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  html: ^0.15.0
  cookie_jar: ^3.0.1
  crypto: ^3.0.2
  cryptography: ^2.0.5
  cryptography_flutter: ^2.0.2
  crypton: ^2.0.5
  archive: ^3.3.1
  pointycastle: ^3.6.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
